# Generated by Django 5.0.3 on 2024-03-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
